### ISSUE TITLE
Doesn't appear to work in Windows.

### ISSUE THREAD

**Issue by kellyselden** [watson/test-all-versions#7]
```
C:\code\eslint-plugin-json-files>tav    
-- required packages ["eslint@6.0.1"]
-- installing ["eslint@6.0.1"]       
-- error installing ["eslint@6.0.1"] ('C:\Program' is not recognized as an internal or external command,
operable program or batch file.
) - retrying (2/10)...
-- installing ["eslint@6.0.1"]
-- error installing ["eslint@6.0.1"] ('C:\Program' is not recognized as an internal or external command,
operable program or batch file.
) - retrying (3/10)...
-- installing ["eslint@6.0.1"]
-- error installing ["eslint@6.0.1"] ('C:\Program' is not recognized as an internal or external command,
operable program or batch file.
) - retrying (4/10)...
-- installing ["eslint@6.0.1"]
-- error installing ["eslint@6.0.1"] ('C:\Program' is not recognized as an internal or external command,
operable program or batch file.
) - retrying (5/10)...
-- installing ["eslint@6.0.1"]
-- error installing ["eslint@6.0.1"] ('C:\Program' is not recognized as an internal or external command,
operable program or batch file.
) - retrying (6/10)...
-- installing ["eslint@6.0.1"]
-- error installing ["eslint@6.0.1"] ('C:\Program' is not recognized as an internal or external command,
operable program or batch file.
) - retrying (7/10)...
-- installing ["eslint@6.0.1"]
-- error installing ["eslint@6.0.1"] ('C:\Program' is not recognized as an internal or external command,
operable program or batch file.
) - retrying (8/10)...
-- installing ["eslint@6.0.1"]
-- error installing ["eslint@6.0.1"] ('C:\Program' is not recognized as an internal or external command,
operable program or batch file.
) - retrying (9/10)...
-- installing ["eslint@6.0.1"]
-- error installing ["eslint@6.0.1"] ('C:\Program' is not recognized as an internal or external command,
operable program or batch file.
) - retrying (10/10)...
-- installing ["eslint@6.0.1"]
-- error installing ["eslint@6.0.1"] - aborting!
Error: 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.<anonymous> (C:\code\eslint-plugin-json-files\node_modules\spawn-npm-install\index.js:60:10)
    at Object.onceWrapper (events.js:291:20)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
-- fatal: undefined
```

**Comment by ashokduraik** [comment]
same issue. could any one tell me a solution
